trigger:
  branches:
    include:
      - azure

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build --if-present
  displayName: 'npm install, build'


- task: AzureWebApp@1
  inputs:
    azureSubscription: $(connection_name)
    appName: $(app_name)
    package: '$(System.DefaultWorkingDirectory)/'
  displayName: 'Deploy to Azure Web App'