# File: .github/workflows/workflow.yml

on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master

    - name: Setup Node 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: 'npm install, build'
      run: |
        npm install
        npm run build --if-present

    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with:
        app-name: bote815fe
        publish-profile: <publishData><publishProfile profileName="bote815fe - Web Deploy" publishMethod="MSDeploy" publishUrl="bote815fe.scm.azurewebsites.net:443" msdeploySite="bote815fe" userName="$bote815fe" userPWD="5ujSEPoftS5GXb4fquzybYhJg2iw06Nw3up94p5WWj7fFh4PH3erJ3GKPzrq" destinationAppUrl="https://bote815fe.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="bote815fe - FTP" publishMethod="FTP" publishUrl="ftps://waws-prod-blu-443.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="bote815fe\$bote815fe" userPWD="5ujSEPoftS5GXb4fquzybYhJg2iw06Nw3up94p5WWj7fFh4PH3erJ3GKPzrq" destinationAppUrl="https://bote815fe.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="bote815fe - Zip Deploy" publishMethod="ZipDeploy" publishUrl="bote815fe.scm.azurewebsites.net:443" userName="$bote815fe" userPWD="5ujSEPoftS5GXb4fquzybYhJg2iw06Nw3up94p5WWj7fFh4PH3erJ3GKPzrq" destinationAppUrl="https://bote815fe.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>
        package: .
