# File: .github/workflows/workflow.yml

on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master

    - name: Setup Node 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: 'npm install, build'
      run: |
        npm install
        npm run build --if-present
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: '{"appId": "43f41059-cf7c-479b-82b7-babe42ec9ffe","displayName": "yukuncd","password": "zMa8Q~yz_BitzNMgZ2HRHrVnm0V5Lf0kmCLcrdby","tenant": "72f988bf-86f1-41af-91ab-2d7cd011db47"}'
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with:
        app-name: bot815fe
        package: .
